version: 2
jobs:
  build:
    docker:
      - image: vivekratnavel/hadoop-ozone-build:v1
    steps:
      - checkout
      - run: ./hadoop-ozone/dev-support/checks/build.sh
  checkstyle:
    docker:
      - image: vivekratnavel/hadoop-ozone-build:v1
    steps:
      - checkout
      - run: ./hadoop-ozone/dev-support/checks/checkstyle.sh
  rat:
    docker:
      - image: vivekratnavel/hadoop-ozone-build:v1
    steps:
      - checkout
      - run: ./hadoop-ozone/dev-support/checks/rat.sh
  author:
    docker:
      - image: vivekratnavel/hadoop-ozone-build:v1
    steps:
      - checkout
      - run: ./hadoop-ozone/dev-support/checks/author.sh
workflows:
  version: 2
  ci_run:
    jobs:
      - build
      - checkstyle