# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: build-branch
on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  push:
  schedule:
    - cron: 30 0,12 * * *
env:
  FAIL_FAST: ${{ github.event_name == 'pull_request' }}
jobs:
  compile:
    runs-on: ubuntu-18.04
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    strategy:
      matrix:
        java: [ 8, 11 ]
      fail-fast: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Cache for npm dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Cache for maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-repo-${{ hashFiles('**/pom.xml') }}-${{ matrix.java }}
          restore-keys: |
            maven-repo-${{ hashFiles('**/pom.xml') }}
            maven-repo-
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Run a full build
        run: hadoop-ozone/dev-support/checks/build.sh -Pcoverage -Pdist
      - name: Store binaries for tests
        uses: actions/upload-artifact@v2
        if: matrix.java == '8'
        with:
          name: ozone-bin
          path: hadoop-ozone/dist/target/hadoop-ozone*.tar.gz
          retention-days: 1
      - name: Delete temporary build artifacts before caching
        run: |
          #Never cache local artifacts
          rm -rf ~/.m2/repository/org/apache/hadoop/hadoop-hdds*
          rm -rf ~/.m2/repository/org/apache/hadoop/hadoop-ozone*
        if: always()
  dependency:
    needs: compile
    runs-on: ubuntu-18.04
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Download compiled Ozone binaries
        uses: actions/download-artifact@v2
        with:
          name: ozone-bin
      - name: Untar binaries
        run: |
          mkdir dist
          tar --strip-components=1 xzf hadoop-ozone*.tar.gz -C dist
      - name: Execute tests
        run: |
          export OZONE_DIST_DIR=`pwd`/dist
          ./hadoop-ozone/dev-support/checks/dependency.sh
      - name: Archive build results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: dependency
          path: target/dependency
        continue-on-error: true
