# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: build-branch
on:
  - push
jobs:
  build:
    name: compile
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/buildenv
        with:
          args: ./hadoop-ozone/dev-support/checks/build.sh
  it-freon:
    name: it-freon
    runs-on: ubuntu-18.04
    needs:
        - build
    steps:
        - run: sudo mkdir mnt && sudo mount --bind /mnt `pwd`/mnt && sudo chmod 777 mnt
        - uses: actions/checkout@master
          with:
            path: mnt/ozone
        - uses: ./mnt/ozone/.github/buildenv
          with:
             args: ./mnt/ozone/hadoop-ozone/dev-support/checks/integration.sh -Pfreon
        - uses: actions/upload-artifact@master
          if: always()
          with:
            name: it-freon
            path: mnt/ozone/target/integration
  coverage:
    name: coverage
    runs-on: ubuntu-18.04
    needs:
#      - it-ozone
      #      - it-hdds-om
      #- it-client
      #      - it-filesystem-contract
      #      - it-filesystem
      - it-freon
    #      - unit
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/buildenv
        with:
          args: ./hadoop-ozone/dev-support/checks/build.sh
      - uses: actions/download-artifact@v2
        with:
          path: target/artifacts
      - run: find -type f
      - run: ./.github/coverage-report.sh
      - uses: actions/upload-artifact@master
        with:
          name: coverage
          path: target/coverage
